### ISSUE TITLE
modified time on /proc/PID is not correct

### ISSUE THREAD

**Issue by fridim** [irexiz/process_uptime#1]
Hello,

```
        let uptime = metadata.modified()?.elapsed()?;
```

That's wrong, the modified time in /proc is usually more recent than the start time of the process.
 Linux exposes the proc tree "lazily". It's created on first read.

```
$ echo $$; date
2650914
2021-12-19T13:58:07 UTC
$ ls -ld /proc/$$; date
dr-xr-xr-x 9 myuser users 0 Dec 19 14:00 /proc/2650914
2021-12-19T14:00:28 UTC
```

Correct fallback implementation (for linux) should use `/proc/PID/stat` file content, column 22:

>               (22) starttime  %llu
>                      The time the process started after system boot.  In kernels before Linux 2.6,  this  value  was
>                      expressed  in  jiffies.   Since  Linux  2.6,  the  value is expressed in clock ticks (divide by
>                      sysconf(_SC_CLK_TCK)).
> 
>                      The format for this field was %lu before Linux 2.6.

And calculate it, i think you can use `libc::_SC_CLK_TCK`.

**Comment by irexiz** [comment]
Thank you for this! I'll check this tomorrow.
